### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SteveDillon123** [stancecoke/Minimal_E-Bike_Torquesensor_Precontroller#1]
Hi,
I hope this is the correct way to ask a question.
I found the excellent information on using a Digispark as a pre-controller for an ebike torque sensor. It's exactly what I have been looking to do, so I have ordered a few Digisparks (which have not yet arrived) and have set up my laptop with Arduino etc.

My background is as a hardware designer, but I have a little experience of various software languages, and some of 'C', so I have been looking through the code to try and understand it, so that I will be confident in making any changes required for my specific setup.

The one section I don't fully understand is lines 34-38 (the PAS pulse coding). I understand the accumulated torque is reduced by 1/32, but (with my limited understanding) it looks as though the torque input is 100% added to the accumulated torque. I would expect that the torque input should be divided by 32 before being added. Am I being silly ?? Am I missing something ??

The other bit I don't get is that the information I have on the NCTE sensor is that it has 8 PAS pulses per revoluution, which would give 16 interrupts per rev -  not 32 as the code is written. Again, am I missing something here ?

I will be using the system with an e-rider torque sensor, which gives 18 PAS pulses per rev, so I'll need to make changes here.

**Comment by stancecoke** [comment]
no problem to ask here, you can find me  at endless sphere or the german Pedelecforum also.
The accumulation of the torque signal is for averaging/filtering. The rightshift defines the number of samples used for averaging. You should set it to value that represents about one crank revolution. 
Some people reported problems with this repo, I think that's an issue of different hardware versions of the tinyspark (and probably clones). There are different pullups on different pins sometimes. But if you are a hardware designer, this should be no problem for you to figure out...

Good Luck with your project!

**Comment by SteveDillon123** [comment]
Hi,
thank you for your reply, I certainly hope my hardware background is
useful.
My biggest hardware problem is the lack of electrical specification on the
e-rider torque sensor - I will need to check the PAS output to make sure it
will not damage the digispark. Because the e-rider runs from a 9v supply,
the PAS output might be a 0v - 9v signal, or it might be an open collector
output which would be better.

I'm still lacking a bit of understanding on one part of the software, maybe
it's my inexperience of C++;
This is my understanding....
In line 36, the variable *torque_kumuliert* is reduced by 1/32 to leave a
number which is 31/32 of the original. The C++ instruction "- =" means
subtract from the original, and the instruction >>5 means shifted 5 bits.
In line 37, the variable* torque_kumiliert* is increased by the 10bit
scaled number from 'analogRead(2)'.
There are a couple of things here that I'm not sure about - the
analogRead(2) implies reading from pin2, but the torque signal is on pin 4.
Secondly, if I add the new torque input to the variable *torque_kumiliert*,
I will end up with 1*new torque+31/32 accumulated torque in the variable. I
think I would expect to divide the new torque by 32 before adding it in to
the accumulated torque.
I'm sure I'm missing something obvious here, but what !

I've found your post on Endless Sphere regarding the KT controllers, which
is what I intend to use. A lot of it is 'way above my head' and I struggle
to understand it all, I keep on going back to it and read it again to try
and gain understanding.

Thanks again for your reply, and your time in helping out.

Steve Dillon

**Comment by stancecoke** [comment]
Perhaps, you can open a thread at Endless Sphere, the discussion may be helpful for other people, too.
There is a good technical description of the ERider:
https://endless-sphere.com/forums/download/file.php?id=279512
The signals of Speed and torque are fully compatible to the tinyspark, don't worry. 
Pin 4 is the ADC Channel 2, so everything is OK ;-)

You have to add a factor in line 42 to bring the signal in a meaningful range. 
https://github.com/stancecoke/Minimal_E-Bike_Torquesensor_Precontroller/blob/854a777767fe161dad41c19796b20d2ca4035f8c/FC_fuer_Arme.ino#L42
Please try to translate the german comments with deepl or other tools. The comments desribe quite exactly what happens in each line.

regards
stancecoke

p.s. when you want to use a Kunteng Controller with our open firmware, you don't need the tinyspark anyway.

**Comment by SteveDillon123** [comment]
I've done as you suggest, and opened a thread on endless sphere in the
Motor Technology forum.
I've had a look at the project
OpenSource-EBike-firmware/BMSBattery_S_controllers_firmware along with the
endless sphere thread.
It's a bit daunting at the moment.
Thanks
Steve Dillon

**Comment by stancecoke** [comment]
Closed.
